import { test, expect } from '@playwright/test';
import { setupIsolatedGame, play, advance, getEngineState } from './helpers/gameTestHelper';
test.beforeEach(async ({ page }) => {
  await setupIsolatedGame(page);
  await play(page);
});
test('movement, rotation and arena bounds use real controls', async ({ page }) => {
  const initial = await getEngineState(page);
  await page.keyboard.down('KeyW');
  await advance(page, 1);
  await page.keyboard.up('KeyW');
  expect((await getEngineState(page)).player.y).toBeGreaterThan(initial.player.y);
  await page.keyboard.down('KeyA');
  await advance(page, 0.5);
  await page.keyboard.up('KeyA');
  expect((await getEngineState(page)).player.rotation).toBeLessThan(0);
  await page.keyboard.down('KeyW');
  await advance(page, 8);
  await page.keyboard.up('KeyW');
  const state = await getEngineState(page);
  expect(state.onLand).toBe(false);
  expect(state.player.x).toBeGreaterThan(0);
  expect(state.player.x).toBeLessThan(1280);
  expect(state.player.y).toBeGreaterThan(0);
  expect(state.player.y).toBeLessThan(768);
  expect(state.camera.x).toBe(initial.camera.x);
  expect(state.camera.y).toBe(initial.camera.y);
});
test('front shot, broadside directions and cooldown', async ({ page }) => {
  await page.keyboard.down('Space');
  await advance(page, 1 / 60);
  expect((await getEngineState(page)).shots).toBe(1);
  await advance(page, 0.1);
  expect((await getEngineState(page)).shots).toBe(1);
  await page.keyboard.up('Space');
  await page.keyboard.down('KeyQ');
  await advance(page, 1 / 60);
  await page.keyboard.up('KeyQ');
  const state = await getEngineState(page);
  expect(state.shots).toBe(4);
  const side = state.projectiles.filter((shot) => shot.dx > 0.9);
  expect(side).toHaveLength(3);
  expect(new Set(side.map((shot) => shot.y)).size).toBe(3);
  await page.keyboard.down('KeyE');
  await advance(page, 1 / 60);
  await page.keyboard.up('KeyE');
  expect((await getEngineState(page)).projectiles.filter((shot) => shot.dx < -0.9)).toHaveLength(3);
});
test('real projectiles damage and destroy a chaser exactly once', async ({ page }) => {
  await page.evaluate(() => window.__PIXI_TEST_HOOKS__!.encounter('chaser'));
  await page.keyboard.down('Space');
  await advance(page, 1.2);
  await page.keyboard.up('Space');
  expect((await getEngineState(page)).score).toBe(1);
  await advance(page, 1);
  expect((await getEngineState(page)).score).toBe(1);
  expect((await getEngineState(page)).enemyStates).toHaveLength(0);
});
test('both enemy types spawn and shooter attacks cause damage', async ({ page }) => {
  await page.evaluate(() => window.__PIXI_TEST_HOOKS__!.setInvulnerable(true));
  await advance(page, 8);
  const types = (await getEngineState(page)).enemyStates.map((enemy) => enemy.archetype);
  expect(types).toContain('chaser');
  expect(types).toContain('shooter');
  expect(types.filter((type) => type === 'chaser').length).toBeLessThanOrEqual(1);
  await page.evaluate(() => window.__PIXI_TEST_HOOKS__!.encounter('shooter'));
  await page.evaluate(() => window.__PIXI_TEST_HOOKS__!.setInvulnerable(false));
  await advance(page, 6);
  expect((await getEngineState(page)).player.hp).toBeLessThan(4);
});
